---
fixtures:
  repositories:
    concat:
      repo: "https://github.com/simp/puppetlabs-concat"
      branch: 'simp-master'
    simplib: "https://github.com/simp/pupmod-simp-simplib"
    stdlib:
      repo: "https://github.com/simp/puppetlabs-stdlib"
      branch: "master"
  symlinks:
    tcpwrappers: "#{source_dir}"
